(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-install-install-confirm nil)
 '(auto-install-replace-confirm nil)
 '(auto-install-save-confirm nil)
 '(auto-save-file-name-transforms (quote (("\\`.*\\([^/]*\\)\\'" "~/.emacs.d/autosave/\\1" t))))
 '(backup-directory-alist (quote (("." . "~/.emacs.d/backups"))))
 '(c-backslash-column 99)
 '(c-basic-offset 4)
 '(column-number-mode t)
 '(comment-column 60)
 '(comment-fill-column 160)
 '(compilation-ask-about-save nil)
 '(csv-align-padding 0)
 '(csv-comment-start-default "#")
 '(csv-field-quotes nil)
 '(csv-header-lines 0)
 '(csv-separators (quote ("|")))
 '(dabbrev-abbrev-char-regexp "\\sw")
 '(debug-on-error nil)
 '(default-input-method "latin-1-prefix")
 '(diff-mode-hook (quote ((lambda nil (diff-auto-refine-mode 1)))))
 '(diff-switches "-u")
 '(fill-column 98)
 '(flyspell-delay 30)
 '(flyspell-delayed-commands nil)
 '(global-auto-revert-mode nil)
 '(global-highlight-changes-mode t)
 '(global-subword-mode t)
 '(global-visual-line-mode nil)
 '(global-whitespace-mode nil)
 '(highlight-changes-colors nil)
 '(highlight-changes-face-list nil)
 '(highlight-changes-global-changes-existing-buffers t)
 '(hippie-expand-dabbrev-as-symbol nil)
 '(hippie-expand-try-functions-list (quote (try-complete-file-name-partially try-complete-file-name try-expand-dabbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill try-expand-all-abbrevs try-expand-line try-expand-list)))
 '(hs-isearch-open nil)
 '(ido-mode (quote both) nil (ido))
 '(indent-tabs-mode nil)
 '(ispell-dictionary "deutsch8")
 '(ispell-extra-args (quote ("--sug-mode=ultra")))
 '(ispell-program-name "c:/cygwin/bin/aspell.exe")
 '(line-move-visual nil)
 '(ls-lisp-dirs-first t)
 '(nxml-child-indent 4)
 '(nxml-where-global-mode nil)
 '(nxml-where-header nil)
 '(pop-up-windows nil)
 '(rng-validate-chunk-size 2000)
 '(rng-validate-delay 3)
 '(rng-validate-quick-delay 1.5)
 '(save-place t nil (saveplace))
 '(server-done-hook (quote (delete-frame)))
 '(server-mode t)
 '(server-temp-file-regexp "^/tmp/Re\\|/draft\\|.*/itsalltext/.*$")
 '(server-window (quote switch-to-buffer-other-frame))
 '(show-paren-mode t)
 '(tab-width 4)
 '(tags-case-fold-search nil)
 '(tool-bar-mode nil)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(visual-line-fringe-indicators (quote (left-curly-arrow right-curly-arrow)))
 '(which-func-modes (quote (nxml-mode emacs-lisp-mode c-mode c++-mode perl-mode cperl-mode python-mode makefile-mode sh-mode fortran-mode f90-mode ada-mode diff-mode)))
 '(which-function-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "SystemWindow" :foreground "SystemWindowText" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 90 :width normal :foundry "outline" :family "Courier New"))))
 '(highlight-changes ((t (:background "alice blue"))))
 '(highlight-changes-delete ((t (:background "bisque1"))))
 '(textile-acronym-face ((t (:foreground "medium blue"))))
 '(textile-blockquote-face ((t (:foreground "midnight blue"))))
 '(textile-code-face ((t (:foreground "firebrick4"))))
 '(textile-pre-face ((t (:foreground "dark green")))))
(put 'narrow-to-region 'disabled nil)
