;;; codex-ide-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from codex-ide.el

(autoload 'codex-ide "codex-ide"
"Start Codex for the current project, or toggle its active window.
With PREFIX, start another Codex session for the current project.

(fn &optional PREFIX)" t)
(autoload 'codex-ide-new-session "codex-ide"
"Start another Codex session for the current project." t)
(autoload 'codex-ide-resume-last "codex-ide"
"Resume the most recent Codex session for the current project." t)
(autoload 'codex-ide-resume "codex-ide"
"Resume a saved Codex session chosen from known rollout ids.
Uses `codex resume <session-id>'.  Prefer `codex-ide-resume-last' for
the most recent session without a picker." t)
(autoload 'codex-ide-stop "codex-ide"
"Stop the active Codex session for the current project.
Other live sessions under the same project root are left running.
Use `codex-ide-list-project-sessions' or `codex-ide-toggle' to switch
before stopping a different session." t)
(autoload 'codex-ide-toggle "codex-ide"
"Cycle live Codex sessions for the current project." t)
(autoload 'codex-ide-switch-to-buffer "codex-ide"
"Switch to the Codex buffer for the current project.
If it is not visible, display it with `codex-ide-display-buffer-function'." t)
(autoload 'codex-ide-list-project-sessions "codex-ide"
"Switch to a live Codex terminal session for the current project." t)
(autoload 'codex-ide-list-sessions "codex-ide"
"Switch to any live Codex terminal session." t)
(autoload 'codex-ide-send-prompt "codex-ide"
"Send PROMPT to the Codex terminal for the current project.
Interactively, read PROMPT from the minibuffer.

(fn &optional PROMPT)" t)
(autoload 'codex-ide-send-escape "codex-ide"
"Send ESC to the Codex terminal for the current project." t)
(autoload 'codex-ide-return-live "codex-ide"
"Restore terminal input and follow the live Codex frame." t)
(autoload 'codex-ide-insert-newline "codex-ide"
"Insert a literal newline into the Codex prompt.
Sends backslash followed by RET, which Codex interprets as a newline." t)
(autoload 'codex-ide-check-status "codex-ide"
"Check whether the Codex CLI is available and report its version." t)
(register-definition-prefixes "codex-ide" '("codex-ide-"))


;;; Generated autoloads from codex-ide-context.el

(defvar codex-ide-context-mode nil
"Non-nil if Codex-Ide-Context mode is enabled.
See the `codex-ide-context-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `codex-ide-context-mode'.")
(custom-autoload 'codex-ide-context-mode "codex-ide-context" nil)
(autoload 'codex-ide-context-mode "codex-ide-context"
"Toggle the global Codex IDE context provider.

This is a global minor mode.  If called interactively, toggle the
`Codex-Ide-Context mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='codex-ide-context-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'codex-ide-context-start "codex-ide-context"
"Start the Codex IDE context IPC provider." t)
(autoload 'codex-ide-context-stop "codex-ide-context"
"Stop the Codex IDE context IPC provider." t)
(autoload 'codex-ide-context-status "codex-ide-context"
"Report whether the Codex IDE context provider is running." t)
(autoload 'codex-ide-send-selection "codex-ide-context"
"Compatibility command for pushing context to connected Codex clients.
WORKSPACE-ROOT defaults to `default-directory'.  If no client is
connected, copy the active selection to the kill ring when present and
tell the user to use `/ide' in the Codex TUI.

(fn &optional WORKSPACE-ROOT)" t)
(register-definition-prefixes "codex-ide-context" '("codex-ide-context-"))


;;; Generated autoloads from codex-ide-debug.el

(autoload 'codex-ide-show-debug "codex-ide-debug"
"Show the `codex-ide' debug buffer." t)
(autoload 'codex-ide-clear-debug "codex-ide-debug"
"Clear the `codex-ide' debug buffer." t)
(register-definition-prefixes "codex-ide-debug" '("codex-ide-"))


;;; Generated autoloads from codex-ide-diff.el

(autoload 'codex-ide-diff-preview "codex-ide-diff"
"Preview a diff between OLD-CONTENT and NEW-CONTENT for FILE-PATH.
Builds temp buffers, runs ediff, prompts for accept/reject, and cleans
up.  Returns t if accepted, nil if rejected.

(fn OLD-CONTENT NEW-CONTENT FILE-PATH)" t)
(register-definition-prefixes "codex-ide-diff" '("codex-ide-diff-"))


;;; Generated autoloads from codex-ide-mcp.el

(autoload 'codex-ide-mcp-start "codex-ide-mcp"
"Start the local Codex MCP tools server." t)
(autoload 'codex-ide-mcp-stop "codex-ide-mcp"
"Stop the local Codex MCP tools server." t)
(autoload 'codex-ide-mcp-status "codex-ide-mcp"
"Report the local Codex MCP tools server status." t)
(autoload 'codex-ide-mcp-install-codex-config "codex-ide-mcp"
"Add the running Emacs MCP server to Codex config after confirmation." t)
(register-definition-prefixes "codex-ide-mcp" '("codex-ide-mcp--"))


;;; Generated autoloads from codex-ide-mcp-core.el

(register-definition-prefixes "codex-ide-mcp-core" '("codex-ide-mcp-"))


;;; Generated autoloads from codex-ide-mcp-protocol.el

(register-definition-prefixes "codex-ide-mcp-protocol" '("codex-ide-mcp--"))


;;; Generated autoloads from codex-ide-mcp-server.el

(register-definition-prefixes "codex-ide-mcp-server" '("codex-ide-mcp-"))


;;; Generated autoloads from codex-ide-mcp-tools.el

(register-definition-prefixes "codex-ide-mcp-tools" '("codex-ide-"))


;;; Generated autoloads from codex-ide-mcp-treesit.el

(register-definition-prefixes "codex-ide-mcp-treesit" '("codex-ide-mcp--tree"))


;;; Generated autoloads from codex-ide-menu.el

(autoload 'codex-ide-menu "codex-ide-menu"
"Open the codex-ide popup menu." t)
(register-definition-prefixes "codex-ide-menu" '("codex-ide-menu--s"))


;;; Generated autoloads from codex-ide-term.el

(register-definition-prefixes "codex-ide-term" '("codex-ide-term"))


;;; Generated autoloads from codex-ide-term-eat.el

(register-definition-prefixes "codex-ide-term-eat" '("codex-ide-term-"))


;;; Generated autoloads from codex-ide-term-vterm.el

(register-definition-prefixes "codex-ide-term-vterm" '("codex-ide-term-vterm--"))

;;; End of scraped data

(provide 'codex-ide-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; codex-ide-autoloads.el ends here
